### ISSUE TITLE
Failing regression tests for a Sanitizer build

### ISSUE THREAD

**Issue by fbrausse** [esbmc/esbmc#1383]
When running a CMAKE_BUILD_TYPE=Sanitizer build on Linux over the regression tests, I'm getting `573 tests failed`. Summary:
- 19x in esbmc-solidity
- ~39x in esbmc-cpp11~
- ~352x in esbmc-cpp~
- ~138x in cuda~

The remaining ones:
- Interval Analysis - Add Arithmetic (Failed)
- Interval Analysis - Add Range Arithmetic (Failed)
- Interval Analysis - Arithmetic Right Shift (Failed)
- Interval Analysis - Base Sign (Failed)
- Interval Analysis - Base Unsigned (Failed)
- Interval Analysis - Bitand (Failed)
- Interval Analysis - Bitor (Failed)
- Interval Analysis - Div Arithmetic (signed) (Failed)
- Interval Analysis - If/Else Statement LHS (Negative) (Failed)
- Interval Analysis - If/Else Statement LHS (Signed) (Failed)
- Interval Analysis - If/Else Statement LHS (Unsigned) (Failed)
- Interval Analysis - If/Else Statement LHS and RHS (Failed)
- Interval Analysis - If/Else Statement RHS (Failed)
- Interval Analysis - If/Else Statement RHS (Negative) (Failed)
- Interval Analysis - Left Shift (Failed)
- Interval Analysis - Right Shift (Failed)
- Interval Analysis - Sub Arithmetic (Failed)
- Interval Analysis - Ternary (Failed)
- Interval Analysis - Ternary (false) (Failed)
- Interval Analysis - Ternary (true) (Failed)
- Interval Analysis - While Statement (Failed)
- Scenario: the loop unroller detects bounded loops (Failed)
- regression/esbmc-old/github_597_oldfrontend_1 (Failed)
- regression/esbmc-old/github_597_oldfrontend_2 (Failed)
- regression/esbmc-old/github_839 (Failed)

Full list: [ctest.summary.txt](https://github.com/esbmc/esbmc/files/12748475/ctest.summary.txt)

*Edit:* I should say that this is after removing the `--memlimit` from the C++ tests via #1382.

**Comment by fbrausse** [comment]
More statistics:
- 28x LeakSanitizer: detected memory leaks
- 531x AddressSanitizer: stack-use-after-scope
- 15x AddressSanitizer: heap-buffer-overflow
- 4x AddressSanitizer: stack-buffer-overflow

**Comment by fbrausse** [comment]
The AddressSanitizer: heap-buffer-overflow ones are all for solidity and have the same backtrace (modulo addresses, of course):
```
READ of size 1 at 0x612000001dde thread T0
    #0 0x55f33f5d5c67 in bool __gnu_cxx::__ops::_Iter_equals_val<char const>::operator()<__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >(__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >) /usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/bits/predefined_ops.h:270
    #1 0x55f33f5d5c67 in std::iterator_traits<__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::difference_type std::__count_if<__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__ops::_Iter_equals_val<char const> >(__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__ops::_Iter_equals_val<char const>) /usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/bits/stl_algobase.h:2123
    #2 0x55f33f5d5c67 in std::iterator_traits<__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::difference_type std::count<__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char>(__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char const&) /usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/bits/stl_algo.h:4034
    #3 0x55f33f5d5c67 in solidity_convertert::get_line_number(nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > const&, bool) src/solidity-frontend/solidity_convert.cpp:2762
    #4 0x55f33f5d6620 in solidity_convertert::get_final_location_from_stmt(nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > const&, locationt&) src/solidity-frontend/solidity_convert.cpp:2820
    #5 0x55f33f61c402 in solidity_convertert::get_block(nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > const&, exprt&) src/solidity-frontend/solidity_convert.cpp:729
    #6 0x55f33f61ec4f in solidity_convertert::get_function_definition(nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > const&) src/solidity-frontend/solidity_convert.cpp:620
    #7 0x55f33f61f911 in solidity_convertert::get_decl(nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > const&, exprt&) src/solidity-frontend/solidity_convert.cpp:161
    #8 0x55f33f6205f5 in solidity_convertert::convert_ast_nodes(nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > const&) src/solidity-frontend/solidity_convert.cpp:130
    #9 0x55f33f623c75 in solidity_convertert::convert() src/solidity-frontend/solidity_convert.cpp:97
    #10 0x55f33f583db5 in solidity_languaget::typecheck(contextt&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) src/solidity-frontend/solidity_language.cpp:110
    #11 0x55f33f0f35cc in language_filest::typecheck(contextt&) src/util/language_file.cpp:88
    #12 0x55f33f08ccd6 in language_uit::typecheck() src/langapi/language_ui.cpp:102
    #13 0x55f33e8b5d80 in esbmc_parseoptionst::parse_goto_program(optionst&, goto_functionst&) src/esbmc/esbmc_parseoptions.cpp:1587
    #14 0x55f33e8b3d2a in esbmc_parseoptionst::create_goto_program(optionst&, goto_functionst&) src/esbmc/esbmc_parseoptions.cpp:1518
    #15 0x55f33e8b2225 in esbmc_parseoptionst::get_goto_program(optionst&, goto_functionst&) src/esbmc/esbmc_parseoptions.cpp:1448
    #16 0x55f33e8d8983 in esbmc_parseoptionst::doit() src/esbmc/esbmc_parseoptions.cpp:505
    #17 0x55f33f0fb3d0 in parseoptions_baset::main() src/util/parseoptions.cpp:71
    #18 0x55f33e8ab433 in main src/esbmc/main.cpp:10
    #19 0x7fe230a4a8c9  (/lib64/libc.so.6+0x238c9)
    #20 0x7fe230a4a984 in __libc_start_main (/lib64/libc.so.6+0x23984)
    #21 0x55f33e8ab070 in _start (debug/src/esbmc/esbmc+0x239070)
```
*Edit:* All 4 AddressSanitizer: stack-buffer-overflow are also in solidity_convertert::get_line_number().

**Comment by fbrausse** [comment]
The C++/CUDA ones have been fixed by #1384. Remaining are 44: solidity, the 3 in esbmc-old and the unit tests from the initial post.

**Comment by rafaelsamenezes** [comment]
> and the unit tests from the initial post

I will take a look.
