### ISSUE TITLE
Makefile builds are not working

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#1479]
Since Ubuntu 22.04 using CMake to generate Makefile builds is resulting in crashes during the build process:

```
[ 21%] Converting ubuntu20.04/kernel_5.15.0-76/include/linux/spinlock.h to data
Traceback (most recent call last):
  File "/home/esbmc/ESBMC_Project/esbmc/scripts/flail.py", line 226, in <module>
    main()
  File "/home/esbmc/ESBMC_Project/esbmc/scripts/flail.py", line 208, in main
    with open(args.output, 'w') as output:
FileNotFoundError: [Errno 2] No such file or directory: '/home/esbmc/ESBMC_Project/esbmc/build/src/c2goto/headers/ubuntu20.04/kernel_5.15.0-76/include/linux/spinlock.h.c'
```

I am not sure how to handle this as the file dependency is stated and other Generators (Ninja, Visual Studio and xcode) are fine.

**Comment by rafaelsamenezes** [comment]
No longer valid.
