### ISSUE TITLE
Our esbmc-wrapper is broken

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#389]
python2 ./esbmc-wrapper.py.2 -s incr -c -p /home/rafaelsa/sv-benchmarks/c/properties/unreach-call.prp /home/rafaelsa
/sv-benchmarks/c/pthread/fib_bench-1.i

```
Traceback (most recent call last):
  File "./esbmc-wrapper.py.2", line 322, in <module>
    result = verify(strategy, category_property, concurrency)
  File "./esbmc-wrapper.py.2", line 266, in verify
    esbmc_command_line = get_command_line(strat, prop, arch, benchmark, concurrency)
  File "./esbmc-wrapper.py.2", line 211, in get_command_line
    command_line = esbmc_path + esbmc_dargs
UnboundLocalError: local variable 'esbmc_dargs' referenced before assignment
```

**Comment by mikhailramalho** [comment]
@rafaelsamenezes, was this fixed?
